更新逻辑

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,30 +18,30 @@ jobs:
 
       - name: downloading addons
         run: |
-          wget -q --show-progress -O official.zip https://github.com/home-assistant/addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O community.zip https://github.com/hassio-addons/repository/archive/refs/heads/master.zip &
-          wget -q --show-progress -O alexbelgium.zip https://github.com/alexbelgium/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O Poeschl.zip https://github.com/Poeschl-HomeAssistant-Addons/repository/archive/refs/heads/main.zip &
-          wget -q --show-progress -O erik73.zip https://github.com/erik73/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O einschmidt.zip https://github.com/einschmidt/hassio-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O FaserF.zip https://github.com/FaserF/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O jdeath.zip https://github.com/jdeath/homeassistant-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O hacs.zip https://github.com/hacs/addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O bluemaes.zip https://github.com/bluemaex/home-assistant-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O expaso.zip https://github.com/expaso/hassos-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O blakeblackshear.zip https://github.com/blakeblackshear/frigate-hass-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O music-assistant.zip https://github.com/music-assistant/home-assistant-addon/archive/refs/heads/main.zip &
-          wget -q --show-progress -O esphome.zip https://github.com/esphome/home-assistant-addon/archive/refs/heads/main.zip &
-          wget -q --show-progress -O litinoveweedle.zip https://github.com/litinoveweedle/hassio-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O brenner-tobias.zip https://github.com/brenner-tobias/ha-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O sanderdw.zip https://github.com/sanderdw/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O dianlight.zip https://github.com/dianlight/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O hydroqc.zip https://gitlab.com/hydroqc/hydroqc-hass-addons/-/archive/main/hydroqc-hass-addons-main.zip &
-          wget -q --show-progress -O hass-broadlink-ac-mqtt.zip https://github.com/Arbuzov/hass-broadlink-ac-mqtt/archive/refs/heads/master.zip &
-          wget -q --show-progress -O hugobloem.zip https://github.com/hugobloem/homeassistant-addons/archive/refs/heads/main.zip &
-          wget -q --show-progress -O haberda.zip https://github.com/haberda/hassio_addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O AlexxIT.zip https://github.com/AlexxIT/hassio-addons/archive/refs/heads/master.zip &
-          wget -q --show-progress -O da-anda.zip https://github.com/da-anda/hass-io-addons/archive/refs/heads/main.zip &
+          wget -q -O official.zip https://github.com/home-assistant/addons/archive/refs/heads/master.zip &
+          wget -q -O community.zip https://github.com/hassio-addons/repository/archive/refs/heads/master.zip &
+          wget -q -O alexbelgium.zip https://github.com/alexbelgium/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O Poeschl.zip https://github.com/Poeschl-HomeAssistant-Addons/repository/archive/refs/heads/main.zip &
+          wget -q -O erik73.zip https://github.com/erik73/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O einschmidt.zip https://github.com/einschmidt/hassio-addons/archive/refs/heads/main.zip &
+          wget -q -O FaserF.zip https://github.com/FaserF/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O jdeath.zip https://github.com/jdeath/homeassistant-addons/archive/refs/heads/main.zip &
+          wget -q -O hacs.zip https://github.com/hacs/addons/archive/refs/heads/main.zip &
+          wget -q -O bluemaes.zip https://github.com/bluemaex/home-assistant-addons/archive/refs/heads/main.zip &
+          wget -q -O expaso.zip https://github.com/expaso/hassos-addons/archive/refs/heads/main.zip &
+          wget -q -O blakeblackshear.zip https://github.com/blakeblackshear/frigate-hass-addons/archive/refs/heads/main.zip &
+          wget -q -O music-assistant.zip https://github.com/music-assistant/home-assistant-addon/archive/refs/heads/main.zip &
+          wget -q -O esphome.zip https://github.com/esphome/home-assistant-addon/archive/refs/heads/main.zip &
+          wget -q -O litinoveweedle.zip https://github.com/litinoveweedle/hassio-addons/archive/refs/heads/main.zip &
+          wget -q -O brenner-tobias.zip https://github.com/brenner-tobias/ha-addons/archive/refs/heads/main.zip &
+          wget -q -O sanderdw.zip https://github.com/sanderdw/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O dianlight.zip https://github.com/dianlight/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O hydroqc.zip https://gitlab.com/hydroqc/hydroqc-hass-addons/-/archive/main/hydroqc-hass-addons-main.zip &
+          wget -q -O hass-broadlink-ac-mqtt.zip https://github.com/Arbuzov/hass-broadlink-ac-mqtt/archive/refs/heads/master.zip &
+          wget -q -O hugobloem.zip https://github.com/hugobloem/homeassistant-addons/archive/refs/heads/main.zip &
+          wget -q -O haberda.zip https://github.com/haberda/hassio_addons/archive/refs/heads/master.zip &
+          wget -q -O AlexxIT.zip https://github.com/AlexxIT/hassio-addons/archive/refs/heads/master.zip &
+          wget -q -O da-anda.zip https://github.com/da-anda/hass-io-addons/archive/refs/heads/main.zip &
           wait
       - name: extract the addons
         run: |
@@ -49,38 +49,26 @@ jobs:
             unzip -o "$file" -d addons && rm "$file"
           done
 
-          
+
       - name: Check and clean up addons
         run: |
-          # 遍历 ./addons 目录下的所有文件夹
           for addon_dir in ./addons/*/; do
-            # 获取文件夹名（例如：home-assistant-addons-main）
             repo_name=$(basename "$addon_dir")
-
-            # 遍历该 repo 内的所有子文件夹，查找可能的 config.json 文件
             for sub_dir in "./addons/$repo_name/"*/; do
-              # 查找 config.json 文件，假设它的名字可以变化
               config_file=$(find "$sub_dir" -type f -name "config.json" -print -quit)
-
-              # 如果找到了 config.json 文件
               if [[ -n "$config_file" ]]; then
-                # 构造另一个 repo 的 config.json 路径
                 main_config_path="./$repo_name/$(basename "$sub_dir")/config.json"
 
-                # 检查第二个 config.json 文件是否存在
                 if [[ -f "$main_config_path" ]]; then
-                  # 提取版本号
                   addon_version=$(extract_version "$config_file")
                   main_version=$(extract_version "$main_config_path")
 
-                  # 对比版本号
                   if [[ "$addon_version" != "$main_version" ]]; then
                     echo "Version mismatch in $repo_name ($(basename "$sub_dir")):"
                     echo "  Addon version: $addon_version"
                     echo "  Main version: $main_version"
                   else
                     echo "Version match in $repo_name ($(basename "$sub_dir")): $addon_version"
-                    # 删除 ./addons/$repo_name/$(basename "$sub_dir") 目录
                     echo "Deleting $sub_dir"
                     rm -rf "$sub_dir"
                   fi
@@ -88,17 +76,11 @@ jobs:
               fi
             done
           done
-
-          # 提取版本号的函数
           extract_version() {
             local file="$1"
-
-            # 如果文件是标准的 JSON 格式
             if jq -e . "$file" >/dev/null 2>&1; then
-              # 使用 jq 提取 version 字段
               jq -r '.version' "$file"
             else
-              # 如果是非标准格式，使用 grep 和 awk 提取 version
               grep -oP '^version:\s*\K[0-9.]+$' "$file"
             fi
           }
@@ -120,7 +102,7 @@ jobs:
               npm install -g ai-markdown-translator
               find ./addons -type f \( -name "README.md" -o -name "DOCS.md" \) -print0 | xargs -0 -P 4 -I {} sh -c '
                 echo "Translating {}"
-                timeout 20s ai-markdown-translator -i "{}" -o "{}" -l "中文" || echo "{} translation failed or timed out."
+                timeout 30s ai-markdown-translator -i "{}" -o "{}" -l "中文" || echo "{} translation failed or timed out."
               '
           
 
@@ -206,7 +188,7 @@ jobs:
       - name: sync hass-panel
         run: |
           mkdir -p hass-panel hass-panel-beta
-          wget -q --show-progress -O hass-panel.zip https://github.com/mrtian2016/hass-panel/archive/refs/heads/main.zip
+          wget -q -O hass-panel.zip https://github.com/mrtian2016/hass-panel/archive/refs/heads/main.zip
           unzip -o hass-panel.zip -d hass-panel-temp && rm hass-panel.zip
           mv -f hass-panel-temp/hass-panel-main/hass-panel/* hass-panel/
           mv -f hass-panel-temp/hass-panel-main/hass-panel-beta/* hass-panel-beta/
