恢复逻辑

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,22 +45,7 @@ jobs:
             unzip -o "$file" -d addons && rm "$file"
           done
 
-      - name: remove the hidden files
-        run: |
-            find addons/ -name ".*" -exec rm -rf {} +
-            for ITEM in addons/*/*; do
-            BASENAME=$(basename "$ITEM") 
-            TARGET_PATH="./$BASENAME"
-              if [ -f "$ITEM" ]; then
-                rm -f "$ITEM"
-                echo "Deleted $ITEM" 
-              elif [ -d "$ITEM" ]; then
-                rm -rf "$TARGET_PATH"
-                mv -f "$ITEM" "./" || echo "Failed to move directory: $ITEM"
-                echo "Moved directory: $ITEM"
-              fi
-            done
-            rm -rf whisparr # 删除无用的仓库
+
 
 
 
@@ -146,7 +131,22 @@ jobs:
                 }
               done
           
-
+      - name: remove the hidden files
+        run: |
+                  find addons/ -name ".*" -exec rm -rf {} +
+                  for ITEM in addons/*/*; do
+                  BASENAME=$(basename "$ITEM") 
+                  TARGET_PATH="./$BASENAME"
+                    if [ -f "$ITEM" ]; then
+                      rm -f "$ITEM"
+                      echo "Deleted $ITEM" 
+                    elif [ -d "$ITEM" ]; then
+                      rm -rf "$TARGET_PATH"
+                      mv -f "$ITEM" "./" || echo "Failed to move directory: $ITEM"
+                      echo "Moved directory: $ITEM"
+                    fi
+                  done
+                  rm -rf whisparr # 删除无用的仓库
 
       - name: sync hass-panel
         run: |
